---
title: "p8105_hw2_jt3649"
author: "Juan Tang"
date: "`r Sys.Date()`"
output: github_document
---

```{r setup}
library(tidyverse)
library(readxl)
```


## Problem 1
Import datasets. 

Read in and clean the pols-month dataset and clean the names. 
```{r}
pols_month_df = 
  read_csv("pols-month.csv")
pols_month_df = 
  #use clean_name function in the janitor package
  janitor::clean_names(pols_month_df) |>
  #use separate() to break up the variable mon. 
  separate(mon, into = c("year", "month", "day"), sep = "-") |>
  mutate(
    #change the month number to name
    month = as.numeric(month),
    month = month.name[month], 
    #convert year avriable to numeric value
    year = as.numeric(year),
    #add president variable
    president = ifelse(prez_gop == 1, "gop", "dem")
  ) |>
  #remove prez_dem, prez_gop, day variable
  select(-prez_dem, -prez_gop, -day) |>
  #arrange the year, month order
  arrange(year, month)
```

Read in and clean the snp dataset and clean the names. 
```{r}
snp_df = 
  read_csv("snp.csv")
snp_df = 
  #use clean_name function in the janitor package
  janitor::clean_names(snp_df) |>
  #use separate() to break up the variable mon. 
  separate(date, into = c("month", "day", "year"), sep = "/") |>
  mutate(
    #change the month number to name
    month = as.numeric(month),
    month = month.name[month],
    #change the year variable to numeric number
    year = as.numeric(year), 
    #unify the year variable format 
    year = ifelse(year < 50, year + 2000, year + 1900)
    ) |>
  #remove day variable
  select(-day) |>
  #arrange the year, month order
  arrange(year, month)
```

Read in and clean the unemployment dataset
```{r}
unemployment_df = 
  read_csv("unemployment.csv") |>
  pivot_longer(
    #select all columns except "Year" to pivot
    cols = -Year, 
    #put the columns names into a new column "month"
    names_to = "month", 
    #put the unemployment_rate values into a new column "unemployment_rate"
    values_to = "unemployment_rate"
  ) |>
  mutate(
    #match the month abbreviation with month name
    month = month.name[match(month, month.abb)], 
    #match the column name year
    year = Year
  ) |>
  select(year, month, unemployment_rate) |>
  #arrange the year, month variable in order
  arrange(year, month)
```

Merge the datasets
```{r}
merged_data = pols_month_df |>
  #merge snp into pols
  left_join(snp_df, by = c("year", "month")) |>
  #merge unemployment into pols and snp dataset
  left_join(unemployment_df, by = c("year", "month"))
```

This is the merged dataset: 
```{r}
print(merged_data)
```


